version: "3.9"
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  backend:
    build: ./hookex
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hookex
    ports:
      - '4000:4000'
    volumes:
      - ./hookex:/app
    command: [sh, -c, "mix phx.server"]

  pgweb:
    image: sosedoff/pgweb
    command: pgweb --bind=0.0.0.0 --listen=5000
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hookex?sslmode=disable
    depends_on:
      - db

volumes:
  pgdata: